FROM golang:latest

WORKDIR /go/src

RUN apt update \
&& apt install -y vim \
&& go install github.com/cosmtrek/air@latest \
&& go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest \
&& go install github.com/ramya-rao-a/go-outline@latest \
&& go install github.com/nsf/gocode@latest \
&& go install github.com/acroca/go-symbols@latest \
&& go install github.com/fatih/gomodifytags@latest \
&& go install github.com/cweill/gotests/gotests@latest \
&& go install github.com/josharian/impl@latest \
&& go install github.com/haya14busa/goplay/cmd/goplay@latest \
&& go install github.com/go-delve/delve/cmd/dlv@latest \
&& go install honnef.co/go/tools/cmd/staticcheck@latest \
&& go install golang.org/x/lint/golint@latest \
&& go install golang.org/x/tools/gopls@latest



CMD ["bash"]